sudo: required
services:
  - docker

before_install:
  - docker build -t jheinowitz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jheinowitz/react-test npm test

after_success:
  - docker build -t jheinowitz/multi-client ./client
  - docker build -t jheinowitz/multi-server ./server
  - docker build -t jheinowitz/multi-worker ./worker
  - docker build -t jheinowitz/multi-nginx ./nginx
  # log in to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images up
  - docker push jheinowitz/multi-client
  - docker push jheinowitz/multi-server
  - docker push jheinowitz/multi-worker
  - docker push jheinowitz/multi-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-461955714824
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY